### ISSUE TITLE
Optionally allow `keypath_separator` in input dict keys (`unflatten`).

### ISSUE THREAD

**Issue by brynpickering** [fabiocaccamo/python-benedict#367]
We're loading in YAML files where we allow the dot notation in place of nested keys. Therefore, the `keypath_separator` is `.` and I'd like that to remain the separator in the resulting `benedict`.

Therefore: `foo.bar: 1` should be loaded in as `{'foo': {'bar': 1}}` and then be accessible as `my_dict["foo.bar"]` and `my_dict["foo"]["bar"]`.

Interestingly, in the currently `benedict` implementation, I can make this happen for top-level keys containing the keypath separator, as follows:

```python
[In] 
my_dict = {"foo.bar": 1}
my_benedict = benedict()
my_benedict.merge(my_dict)
my_benedict

[Out] 
{'foo': {'bar': 1}}
```

But I get the (expected) error in these two cases:

```python
benedict({"foo.bar": 1})
```

```python
my_dict = {"baz": {"foo.bar": 1}}
my_benedict = benedict()
my_benedict.merge(my_dict)
```

`python-benedict` version: 0.33.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-benedict/issues/367">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/367/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/367/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@brynpickering thanks for reporting this issue.

Correct me if I'm wrong, this is a problem of the `merge` method right?

**Comment by brynpickering** [comment]
Also instatiation. I _want_ `benedict({"baz": {"foo.bar": 1}}, keypath_separator=".")` to work and to be represented internally as `{"baz": {"foo": {"bar": 1}}}`.

The second part of my issue is more of a bug based on the existing expected functionality, but is in the correct direction for the feature I would like 😅

**Comment by fabiocaccamo** [comment]
@brynpickering with https://github.com/fabiocaccamo/python-benedict/commit/d79336dd7362ea1f7faa91c2ec4587bb1aec2824 the behaviour of the `merge` method has been fixed, now if the input `dict` has keys containing `keypath_separator` a `ValueError` is raised (intended behaviour). 

So, with this fix, this issue becomes a feature request instead of a bug report (correct me if I'm wrong).

**Comment by brynpickering** [comment]
Yes, that's correct.

**Comment by brynpickering** [comment]
I had a look at `unflatten`. I think the approach would need to be:

```
f = benedict.from_yaml("my-dict.yml", keypath_separator=None)
d = benedict(f.unflatten(separator="."))  # must wrap to be able to set and get keys with the "." separator 
```

It's not particularly pretty and potentially involves creating the same representation of data in memory three times (I haven't looked into exactly what goes on under the hood with the data when calling `unflatten` and `benedict`).

You're right that it would be silently backward incompatible, but it seems more intuitive to me that defining the keypath separator on loading data is equivalent to telling benedict that any keys using that separator are _meant_ to be separated. 

Perhaps a flag could be added whenever `keypath_separator` is available as an argument like `separate_on_separator`, `separate`, or `unflatten`. If True, it would separate any keys using the separator into a nested dict. Then it can default to False to achieve the current behaviour.

**Comment by fabiocaccamo** [comment]
@brynpickering considering that it's possible to achieve the desired result in two steps, I don't think I will ever spend time working on this.

**Comment by ultranity** [comment]
> @brynpickering with [d79336d](https://github.com/fabiocaccamo/python-benedict/commit/d79336dd7362ea1f7faa91c2ec4587bb1aec2824) the behaviour of the `merge` method has been fixed, now if the input `dict` has keys containing `keypath_separator` a `ValueError` is raised (intended behaviour).
> 
> So, with this fix, this issue becomes a feature request instead of a bug report (correct me if I'm wrong).

Just found benedict as a dict flatten/unflatten converter candidate, but I would request to revert this/support unflatten feature. Since now we lost the way to unflatten `dict` objects AFAK, unless you dump it to yaml then load then unflatten which obviously lacks of convinence.

Use case purposed by @fabiocaccamo 
benedict({"baz": {"foo.bar": 1}}, keypath_separator=".") to be represented internally as {"baz": {"foo": {"bar": 1}}}.

Purposal:
add an arg(`parse_keypath=False` for example), so that:
- `benedict({"baz": {"foo.bar": 1}}, keypath_separator=".")` stil raise Value Error.
- `benedict({"baz": {"foo.bar": 1}}, keypath_separator=".", parse_keypath=True)` to be represented internally as `{"baz": {"foo": {"bar": 1}}}`.
- `benedict().merge({"baz": {"foo.bar": 1}}, parse_keypath=True)` to be represented internally as `{"baz": {"foo": {"bar": 1}}}`.

For example, pytorch state_dict stores all content in a flattened way, while it will be cool to convert into nested one.
