### ISSUE TITLE
`merge` not working for empty dictionaries

### ISSUE THREAD

**Issue by skshetry** [fabiocaccamo/python-benedict#59]
```python
from benedict import benedict
x = {}
y = benedict(x)
y.merge({"foo": "bar"})
print(x, y)
# In 0.24.1:
# {} {'foo': 'bar'}
# In 0.24.0:
# {'foo': 'bar'} {'foo': 'bar'}
```

This seems to be happening due to e8ccb7270e which does not maintain the pointer to the original dictionary if the dictionary is empty, so looking at the code, it may affect more than just the `merge`.

**Python version**
3.9.4

**Package version**
0.24.1

**Current behavior (bug description)**
The empty dictionary is not updated in-place, but the benedict object is.

**Expected behavior**
The empty dictionary is updated in-place as well as the benedict object.

**Comment by RomainTT** [comment]
I think I found another consequence.

```python
d = benedict()
d["a"] = {}
d["a"]["b"] = {}
print(d)
>>> {'a': {}}
```

As you can see, `b` is missing.

**Comment by simkimsia** [comment]
I think i found the solution and the actual bug. The issue was that the original solution to solve the json.dumps(d) aka `test_issue_0057` is wrong. There's an extra return in `__setitem__` under BaseDict.py. Removing that solved everything.

I have run the full suite locally and everything passed

![image](https://user-images.githubusercontent.com/245021/128621661-32bc5624-7fab-42a1-a6f5-a50fcc7756b5.png)


I will set up a PR.

**Comment by simkimsia** [comment]
Thank you, @skshetry and @RomainTT for writing example test cases so I can create PR #60 which should solve the buggy 0.24.1

**Comment by fabiocaccamo** [comment]
You can upgrade to `0.24.2`.
