### ISSUE TITLE
Flatten with dot separator 

### ISSUE THREAD

**Issue by JJGO** [fabiocaccamo/python-benedict#88]
**Python version**
Python 3.9.12

**Package version**
master (installed with `python -m pip install git+https://github.com/fabiocaccamo/python-benedict.git`)

**Current behavior (bug description)**
flatten does not work with the `.` separator. E.g.

```python
d = benedict({'a': {'b': {'c': 1}}})
d.flatten('.')
# {'a': {'b': {'c': 1}}} 
```

**Expected behavior**

```python
d = benedict({'a': {'b': {'c': 1}}})
d.flatten('.')
# {'a.b.c': 1}
```

**Comment by fabiocaccamo** [comment]
@JJGO the problem here is that you are trying to `flatten` the dict using the same separator used as `keypath_separator` (`'.'` by default), so once flattened, the keys are automatically splitted using the `keypath_separator` and the dict comes back to its initial form.

This behaviour seems the right one to me, an improvement could be to raise a `ValueError` if the flatten separator is equal to the `keypath_separator`. 

What do you think about it?

**Comment by JJGO** [comment]
While that's a reasonable behavior, I think it would be useful to have a couple of methods like these

```python
def asflat(self:benedict) -> dict:
     # returns regular dict with all keys flattened with the keypath_separator

@classmethod
def fromflat(cls, flat_dict: dict, sep:str) -> benedict:
     # returns regular dict by splitting keys by sep and associatively merging the dicts
```

**Comment by fabiocaccamo** [comment]
There is already the `unflatten` method for doing this.
